# inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/factories/*'
    - !ruby/regexp /old_and_unused\.rb$/
