language: ruby
rvm:
  - 2.0.0
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
before_script:
  - mysql -e 'create database flylow_test;'
branches:
  only:
    - develop
    - master
