common: &dev
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
<% if RUBY_PLATFORM =~ /darwin/i %>
  socket: /tmp/mysql.sock
<% elsif RUBY_PLATFORM =~ /linux/i %>
  socket: /var/run/mysqld/mysqld.sock 
<% 
  else
    raise "OS platform not yet configured. Please configure database.yml" 
  end
%>

sqlite: &sqlite
  adapter: sqlite3
  pool: 5
  timeout: 5000

postgres: &postgres  
  adapter: postgresql
  encoding: utf8

development: 
  <<: *sqlite
  database: db/development.sqlite3

test: &test
  <% if ENV['TEST_LOCAL'] %>
    <<: *sqlite
    database: db/test.sqlite3
  <% else %>
    <<: *postgres
    database: hal_fare_test
  <% end %>

production:
  <<: *postgres
  database: ENV['DATABASE_URL']

cucumber:
  <<: *test
