mysql: &mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  encoding: utf8
<% if RUBY_PLATFORM =~ /darwin/i %>
  socket: /tmp/mysql.sock
<% elsif RUBY_PLATFORM =~ /linux/i %>
  socket: /var/run/mysqld/mysqld.sock 
<% 
  else
    raise "OS platform not yet configured. Please configure database.yml" 
  end
%>

sqlite: &sqlite
  adapter: sqlite3
  pool: 5
  timeout: 5000
  # database: db/development.sqlite3

postgres: &postgres  
  adapter: postgresql
  encoding: utf8

development: 
  <<: *mysql
  database: flylow_development

test: &test
  <<: *mysql
  database: flylow_test
  <% if ENV["TRAVIS"] %>
    username: travis
  <% end %>

production:
  <<: *mysql
  database: flylow_production
  username: root
